theme: jekyll-theme-minimal
title: Welcome to Xiaoyu's 2020 GSoC page!
description: It will keep updating every week until the end of August 2020.
logo: [https://github.com/Xiaoyu-Lu/GSoC_2020/blob/master/img/customLogo.gif.png]
